version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - $PWD/docker/nginx:/etc/nginx/conf.d
      - nginxlog:/var/nginx/log

  web:
    build:
      context: .
      dockerfile: $PWD/docker/web/Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      GOOGLE_MAP_API_KEY: ${GOOGLE_MAP_API_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      DATABASE_URL_SPRINGBOOT: jdbc:postgresql://db:5432/itetenosuke
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db
    command: ["java", "-jar", "Itete-no-suke-1.0.0-SNAPSHOT.jar"]

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
  nginxlog:
