spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL_POSTGRES:jdbc:postgresql://localhost:5432/itetenosuke}
    username: ${DATABASE_USER:sukeroku}
    password: ${DATABASE_PASSWORD:D23iKlso3iqoiad}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  messages:
    fallback-to-system-locale: false
  flyway:
    shcemas: sukeroku
    enabled: true
    baseline-on-migrate: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
sendgrid:
  api-key: ${SEND_GRID_API_KEY}
logging:
  file:
    path: /logs
  level:
    root: INFO
# google-map-api:
#     key: ${GOOGLE_MAP_API_KEY}
# open-weather-api:
#     key: ${OPEN_WEATHER_API_KEY}
management:
  endpoints:
    enabled-by-default: false
  #      web:
  #        cors:
  #          allowed-origins: "https://example.com"
  #          allowed-methods: "GET"
  endpoint:
    health:
      enabled: true
server:
  port: ${PORT:8080}
gcp:
  project-id: ${GCP_PROJECT_ID}
  bucket_name: ${GCP_BUCKET_NAME}