name: itetenosuke-cicd
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: itetenosuke-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: build
        run: |
          docker build -f docker/web/Dockerfile .
          bash deploy.sh
