name: itetenosuke-cicd
on:
  push:
    branches:
      - master

jobs:
  build:
    name: itetenosuke-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build /docker/web/Dockerfile
